config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#index'
  post 'jokes/:joke_id/like', to: 'home#like', as: 'like'
  post 'jokes/:joke_id/dislike', to: 'home#dislike', as: 'dislike'
  root 'home#index'
end

app/models/joke.rb
class Joke < ActiveRecord::Base
  has_many :votes, dependent: :destroy
  validates :content, presence: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :joke
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :init_session, only: [:index]
  
  def index
    @joke = get_joke
  end

  def like
    vote("like")
  end

  def dislike
    vote("dislike")
  end

  def init_session
    session[:user_id] ||= Digest::SHA2.hexdigest(Time.now.to_s)
    session[:read_jokes] ||= []
  end

  private
    def get_joke
      Joke.where.not(id: session[:read_jokes]).take(1).first()
    end

    def vote(vote_type)
      # set joke is read
      session[:read_jokes].push(params[:joke_id]) 

      # save joke's vote
      joke = Joke.find(params[:joke_id])
      vote = joke.votes.build(:vote_type => vote_type, :user_id => session[:user_id])

      # respond to client
      respond_to do |format|      
        if vote.save
          format.json { render json: { :joke => get_joke } }
        else
          format.json { render json: vote.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
-if @joke
  .joke-content
    = @joke.content
  .votes
    = link_to 'This is Funny!', like_path(@joke), class: 'btn btn-app btn-blue', id: 'like'
    = link_to 'This is not Funny.', dislike_path(@joke), class: 'btn btn-app btn-green', id: 'dislike'

  :javascript
    $(document).on('click', '#like, #dislike', function(e){
      e.preventDefault();

      $.ajax({
        type: 'POST',
        url: $(this).attr('href'),
        data:{
          joke_id: parseInt("#{@joke.id}")
        },
        success: function (data) {
          if(data.joke){
            $('.joke-content').text(data.joke.content);
            $('#like').attr('href', '/jokes/' + data.joke.id + '/like');
            $('#dislike').attr('href', '/jokes/' + data.joke.id + '/dislike');
          }
          else{
            $('.joke-content').html("<p class='align-center'>That's all the jokes for today! Come back another day!</p>");
            $('.votes').remove();
          }
        },
        error: function (err) {
          console.log('Error when like joke: ' + err);
        }
      });
    });

- else
  .joke-content
    %p.align-center That's all the jokes for today! Come back another day!
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Interview
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    / header
    = render 'partials/header'

    / main content
    #content.container
      = yield

    / footer
    = render 'partials/footer'
    

app/views/partials/_footer.html.haml
%footer.footer.white-bg
  .about
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software.
  .copyright
    Copyright 2015 Futureworkz Pte Ltd. Handcrafted by 
    %a{:href => "#"}
      Joane Futureworkz
      

app/views/partials/_header.html.haml
%nav.navbar.white-bg
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Jokes
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li.profile
          %a{:href => "#"}
            .info
              Handcrafted by
              %strong
                Joan Futureworkz
            .avatar
              = image_tag('user.jpg')
%header.header
  %h2 A joke a day keeps the doctor away
  %p If you joke wrong away, your teeth have to pa. (Serious)
  